### ISSUE TITLE
mac os上icovn没有64位支持

### ISSUE THREAD

**Issue by hanjin8307** [yangyangwithgnu/hardseed#15]
把iconv源码加进去一块编译吧

**Comment by yangyangwithgnu** [comment]
你把
TARGET_LINK_LIBRARIES(hardseed curl)
替换成
TARGET_LINK_LIBRARIES(hardseed curl pthread iconv)
试试有无效果。

**Comment by hanjin8307** [comment]
Undefined symbols for architecture x86_64:
  "_libiconv", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
  "_libiconv_close", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
  "_libiconv_open", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [hardseed] Error 1
make[1]: *** [CMakeFiles/hardseed.dir/all] Error 2
make: *** [all] Error 2

**Comment by hanjin8307** [comment]
link libiconv写全路径就ok了...../usr/local/lib/libiconv.dylib
