### ISSUE TITLE
能否每个帖种子和图片自动保存在同一个子文件夹

### ISSUE THREAD

**Issue by cshlycxt** [yangyangwithgnu/hardseed#17]
rt，确实强大的神器

**Comment by yangyangwithgnu** [comment]
目的是？

**Comment by cshlycxt** [comment]
方便查看，特别是文件数量多了以后。对大神您来讲应当不是难事，希望能下次能顺便整整

**Comment by yangyangwithgnu** [comment]
我的使用习惯，首先，把几百个种子和图片下载下来，接着，浏览图片，觉得可口的留下，不可口的删除（通过图片浏览器直接删除），然后，在种子和图片的大目录中按文件名排序，目录中有图片的种子是要下载的，最后，通过 shift 或 ctrl 多选没有图片的种子，删除之，最后，剩下的全是要下载的种子。

如果，按你所说，相关种子和图片单独一个目录，与我使用习惯相悖，所以，没有办法了。

**Comment by cshlycxt** [comment]
明白了，我已使用批处理解决。谢谢您的回复。

**Comment by cshlycxt** [comment]
期待您写出更好的神器

**Comment by yangyangwithgnu** [comment]
大家一起玩  ~^_^~
