### ISSUE TITLE
种子下载失败？

### ISSUE THREAD

**Issue by cc1024** [yangyangwithgnu/hardseed#22]
种子下载失败，很多都是0kb，无法打开。

**Comment by cc1024** [comment]
代理试过GoAgent，Wallproxy，都会出现这个问题。

**Comment by wuzhefang** [comment]
我用的是ss，也出现这个问题，都是0kb

**Comment by yangyangwithgnu** [comment]
有无报错？

**Comment by Fighter2b** [comment]
代理软件的原因吧。

**Comment by yangyangwithgnu** [comment]
有些 shadowsocks 代理服务器禁止下载，特别是免费的，你换个代理工具再试试。

**Comment by wuzhefang** [comment]
我用的是收费的，如果不能下就都不能下，你有没有合适的服务器，我测试一下。

-- 
Zhefang Wu
Beijing,China

在 2016年2月16日 下午2:02:55, yangyangwithgnu (notifications@github.com) 写到:

有些 shadowsocks 代理服务器禁止下载，特别是免费的，你换个代理工具再试试。

**Comment by yangyangwithgnu** [comment]
用 goagent 试试，这儿有配置好的 https://github.com/yangyangwithgnu/goagent_out_of_box_yang
