### ISSUE TITLE
Mac升级到OS X El Capitan 后无法使用

### ISSUE THREAD

**Issue by ieiayaobb** [yangyangwithgnu/hardseed#26]
错误如下
```
Make Error at cmake_install.cmake:39 (file):
  file INSTALL cannot copy file
  "/Users/shenyineng/Documents/workspace/hardseed/build/hardseed" to
  "/usr/bin/hardseed".
```

**Comment by Rookieup** [comment]
遇到了同样问题，求 fix

**Comment by zgrubby** [comment]
升级到 EI Caption 无法下载图片，文件夹都是空的

**Comment by zgrubby** [comment]
升级到 EI Caption 无法下载图片，文件夹都是空的

**Comment by Rookieup** [comment]
重装不管用，

2015-10-16 17:42 GMT+08:00 Phil <notifications@github.com>:

**Comment by starkshaw** [comment]
El Capitan 重新设置了 `/usr/bin` 的权限而已，编译成功的话仍然可以在当前路径运行。

**Comment by Rookieup** [comment]
谢谢，我试试

2015-10-18 6:05 GMT+08:00 Zhenbang “Stark” Xiao <notifications@github.com>:

**Comment by Bluelich** [comment]
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/El_Capitan_and_Homebrew.md

**Comment by yangyangwithgnu** [comment]
我更新了 CMakeList.txt，请重新构建下，应该没问题了。
