### ISSUE TITLE
无法完成 " make && sudo make install "

### ISSUE THREAD

**Issue by jiaqiluo** [yangyangwithgnu/hardseed#28]
System: OS X El Capitan, 10.11.2
在执行  " make && sudo make install " 时发生如下错误： 

Undefined symbols for architecture x86_64:
  "_iconv", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
  "_iconv_close", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
  "_iconv_open", referenced from:
      Webpage::convertCharset(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in Webpage.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [hardseed] Error 1
make[1]: *** [CMakeFiles/hardseed.dir/all] Error 2
make: *** [all] Error 2

大家有遇到这个问题吗？

**Comment by xianxingg** [comment]
$ sudo port -f deactivate libiconv
$ ... try to clean / rebuild your project...
$ sudo port activate libiconv
$ ... try to clean / rebuild your project...

**Comment by yangyangwithgnu** [comment]
我没 osX 环境，听说 rootless 机制导致的。我更新了 CMakeList.txt，请重新构建下，应该没问题了。
