### ISSUE TITLE
--like后面的关键词区分大小写吗？

### ISSUE THREAD

**Issue by tangxiadi** [yangyangwithgnu/hardseed#29]
--like后面的关键词区分大小写吗？如果区分，如何让它不区分大小写？

**Comment by tangxiadi** [comment]
还有，怎么指定帖子下载图片和种子？比如合集类的帖子，一个帖子多张图片和多个种子，一个一个种子手动下太慢，怎么利用hardseed将它们批量抓取下来？

**Comment by yangyangwithgnu** [comment]
--like 大小写敏感，后续可以调整为不敏感。你喜欢哪些关键字，需要这么严谨 :-]

合集问题请见 Q11
