### ISSUE TITLE
求助：ubuntu14.04LTS 安装失败，cmake处出现问题

### ISSUE THREAD

**Issue by JoannaHu** [yangyangwithgnu/hardseed#31]
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error: your CXX compiler: "CMAKE_CXX_COMPILER-NOTFOUND" was not found.   Please set CMAKE_CXX_COMPILER to a valid compiler path or name.
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 2.8)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/home/joanna/hardseed/build/CMakeFiles/CMakeOutput.log".
See also "/home/joanna/hardseed/build/CMakeFiles/CMakeError.log".

**Comment by lber19535** [comment]
把 cmake_minimum_required(VERSION 2.8) 加到 CMakeList 文件的开头

**Comment by JoannaHu** [comment]
谢谢，已经解决了，要先sudo apt-get install build-essential，之后就没问题了
