### ISSUE TITLE
mac的安装可以优化

### ISSUE THREAD

**Issue by chncwang** [yangyangwithgnu/hardseed#34]
cmake可以判断OS的类型，所以针对mac平台的改动，可以自动化。
另外，我的mac上，哪怕提供sudo权限，都没法把程序cp到/usr/bin/下，cp到/usr/local/bin下则没有问题

**Comment by yanggs07** [comment]
10.11就这样吧。。

**Comment by yangyangwithgnu** [comment]
@chncwang 
按你的建议调整了，不再 cp 到 /usr/bin/ 而是到 /usr/local/bin。另外，空点再把在自动区分 OS 加入 CMakeList.txt 中。
