### ISSUE TITLE
caoliu_selfie没图

### ISSUE THREAD

**Issue by hackjie** [yangyangwithgnu/hardseed#36]
可以显示success，但是本地没图

**Comment by sequencer** [comment]
'''
--- a/src/lib/self/CaoliuTopicWebpage.cpp
+++ b/src/lib/self/CaoliuTopicWebpage.cpp
@@ -78,7 +78,7 @@ parsePicturesUrls (const string& webpage_txt, vector<string>& pictures_urls_list
     }

     // the list may be on the webpage at the same time
-    static const vector<pair<string, string>> begin_and_end_keywords_list = { make_pair("<img src='", "'"), 
+    static const vector<pair<string, string>> begin_and_end_keywords_list = { make_pair("<input src='", "'"), 
'''

**Comment by sequencer** [comment]
手機bug_(:з」∠)_ 將就看吧⋯⋯

**Comment by yangyangwithgnu** [comment]
参见 @sequencer 的 patch。新版已修复。
