### ISSUE TITLE
草榴的挂了 另外上传个自己写的全论坛搜索脚本

### ISSUE THREAD

**Issue by tanekfan** [yangyangwithgnu/hardseed#38]
草榴的挂了 无法获取到了
@yangyangwithgnu 
不能上传*.bat的文件 所以重命名成txt的了 下载后放在/bin/windows目录下

使用方法：
set keywords=苍井空 关键词打在这里
set num=-1 搜索范围打这里
保存然后运行就好了

[runall_upload.bat.txt](https://github.com/yangyangwithgnu/hardseed/files/109976/runall_upload.bat.txt)

**Comment by yangyangwithgnu** [comment]
新的 win 版已修复。另外，外壳 *.bat 有人在 github 上创建了 repo，你可以找找。

**Comment by helloqingfeng** [comment]
@tanekfan @ting723为“硬盘女神”加一个小外壳https://github.com/ting723/hardseedBatShell
