### ISSUE TITLE
2月5号的直接把获取地址的json用了GoAgent代理_(:зゝ∠)_

### ISSUE THREAD

**Issue by hefan121** [yangyangwithgnu/hardseed#45]
static const string portals_file_url("http://raw.githubusercontent.com/yangyangwithgnu/hardseed/master/config/portals_list.json");
    Webpage portals_list_webpage(portals_file_url, "", "http://127.0.0.1:8087");
    if (!portals_list_webpage.isLoaded()) {
        cerr << "ERROR! fail to load " << portals_file_url << endl;
        exit(EXIT_FAILURE);
    }

http://127.0.0.1:8087，表示用ss的很忧伤，自己改成了socks5://127.0.0.1:port

**Comment by Cha0sX** [comment]
+1
这里没有使用代理的配置
