### ISSUE TITLE
portals_list.json

### ISSUE THREAD

**Issue by cokabug** [yangyangwithgnu/hardseed#46]
#我在墙外的机器上运行后返回错误：
ERROR! fail to load http://raw.githubusercontent.com/yangyangwithgnu/hardseed/master/config/portals_list.json

命令行：
hardseed --saveas-path /data/seed --topics-range 8 64 --timeout-download-picture 32 --hate X-Art --proxy ""

**Comment by cokabug** [comment]
但是我直接wget这个文件是没问题的

**Comment by hefan121** [comment]
portals_file_url("http://raw.githubusercontent.com/yangyangwithgnu/hardseed/master/config/portals_list.json");
Webpage portals_list_webpage(portals_file_url, "", "http://127.0.0.1:8087");

把代码里http://127.0.0.1:8087改成你的代理端口

**Comment by cokabug** [comment]
搞定～牛
