### ISSUE TITLE
mac 求助!! There is no topic which you like

### ISSUE THREAD

**Issue by Janking** [yangyangwithgnu/hardseed#58]
附上两张截图，我的操作系统是mac，梯子用的是shadowsock，自动代理模式，能用浏览器打开那俩个网站，现在神器根据视频安装好，却下载不了任何东西！？
![image](https://cloud.githubusercontent.com/assets/4319707/14810169/17f29620-0bc4-11e6-9c6a-5b5435280f0f.png)

![image](https://cloud.githubusercontent.com/assets/4319707/14810227/5f4f04f4-0bc4-11e6-8f98-cc46e5076bbd.png)

**Comment by uncode** [comment]
你开全局可以下载东西不？


在 2016年4月26日 下午3:36:17, Janking (notifications@github.com) 写到:





我用的是shadowsock，自动代理模式，能用浏览器打开那俩个网站，现在神器根据视频安装好，却下载不了任何东西！？

**Comment by Janking** [comment]
@uncode 可以了！是proxy的地址没写对，少个字母……
