### ISSUE TITLE
mac 编译错误 

### ISSUE THREAD

**Issue by whcoding** [yangyangwithgnu/hardseed#79]
➜  build git:(master) cmake .
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.11)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
-- Generating done
-- Build files have been written to: /Users/xxma/Downloads/hardseed/build
➜  build git:(master) ✗ make && make install
Scanning dependencies of target hardseed
[  5%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/main.o
[ 11%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/TopicsListWebpage.o
[ 16%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/AichengTopicsListWebpage.o
[ 22%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/CaoliuTopicsListWebpage.o
[ 27%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/TopicWebpage.o
[ 33%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/AichengTopicWebpage.o
[ 38%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/CaoliuTopicWebpage.o
[ 44%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/SeedWebpage.o
[ 50%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/JandownSeedWebpage.o
[ 55%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/RmdownSeedWebpage.o
[ 61%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/Aicheng.o
[ 66%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/self/Caoliu.o
[ 72%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/helper/Webpage.o
[ 77%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/helper/Time.o
[ 83%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/helper/CmdlineOption.o
[ 88%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/helper/Misc.o
[ 94%] Building CXX object CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/3rd/json11/json11.o
/Users/xxma/Downloads/hardseed/src/lib/3rd/json11/json11.cpp:152:24: error:
      invalid operands to binary expression ('nullptr_t' and 'nullptr_t')
        return m_value < static_cast<const Value<tag, T> *>(other)->m_value;
               ~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/xxma/Downloads/hardseed/src/lib/3rd/json11/json11.cpp:208:5: note: in
      instantiation of member function 'json11::Value<json11::Json::Type::NUL,
      nullptr_t>::less' requested here
    JsonNull() : Value(nullptr) {}
    ^
1 error generated.
make[2]: *** [CMakeFiles/hardseed.dir/Users/xxma/Downloads/hardseed/src/lib/3rd/json11/json11.o] Error 1
make[1]: *** [CMakeFiles/hardseed.dir/all] Error 2
make: *** [all] Error 2

**Comment by oracle9i88** [comment]
问题同上

**Comment by oracle9i88** [comment]
我搞定了

**Comment by oracle9i88** [comment]
重新装一个json11

**Comment by whcoding** [comment]
json11  ???

**Comment by whcoding** [comment]
https://github.com/dropbox/json11  这个东西??

**Comment by arafat5549** [comment]
mac自带llvm的gcc版本太低 用brew安装一个 gcc@5
然后用动态链接链接gcc
            **cd /usr/local/bin
            ln -s gcc-5 gcc
            ln -s g++-5 g++
            ln -s cpp-5 cpp
            ln -s c++-5 c++
            gcc --vserion**
